@echo off
echo Setting up HybridRec++...
call .venv\Scripts\python.exe -m pip install -e .
echo Downloading data...
call .venv\Scripts\python.exe src\download_data.py
echo Launching App...
call .venv\Scripts\python.exe -m streamlit run app\streamlit_app.py
pause
